// flow-typed signature: e759314cc206aa3dd93f204cda6a670b
// flow-typed version: <<STUB>>/muicss_v^0.9.39-rc1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'muicss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'muicss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'muicss/angular' {
  declare module.exports: any;
}

declare module 'muicss/dist/angular/mui-angular' {
  declare module.exports: any;
}

declare module 'muicss/dist/angular/mui-angular.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-angular-combined' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-angular-combined.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-combined' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-combined.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-react-combined' {
  declare module.exports: any;
}

declare module 'muicss/dist/extra/mui-react-combined.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/js/mui' {
  declare module.exports: any;
}

declare module 'muicss/dist/js/mui.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/react/mui-react' {
  declare module.exports: any;
}

declare module 'muicss/dist/react/mui-react.min' {
  declare module.exports: any;
}

declare module 'muicss/dist/webcomponents/mui-webcomponents' {
  declare module.exports: any;
}

declare module 'muicss/dist/webcomponents/mui-webcomponents.min' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/appbar' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/babel-helpers' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/button' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/caret' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/checkbox' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/col' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/container' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/divider' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/dropdown-item' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/dropdown' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/form' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/input' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/option' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/panel' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/radio' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/row' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/select' {
  declare module.exports: any;
}

declare module 'muicss/lib/angular/tabs' {
  declare module.exports: any;
}

declare module 'muicss/lib/js/config' {
  declare module.exports: any;
}

declare module 'muicss/lib/js/lib/forms' {
  declare module.exports: any;
}

declare module 'muicss/lib/js/lib/jqLite' {
  declare module.exports: any;
}

declare module 'muicss/lib/js/lib/util' {
  declare module.exports: any;
}

declare module 'muicss/lib/js/overlay' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/_helpers' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/_textfieldHelpers' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/appbar' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/babel-helpers' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/button' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/caret' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/checkbox' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/col' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/container' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/divider' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/dropdown-item' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/dropdown' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/form' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/input' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/option' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/panel' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/radio' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/row' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/select' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/tab' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/tabs' {
  declare module.exports: any;
}

declare module 'muicss/lib/react/textarea' {
  declare module.exports: any;
}

declare module 'muicss/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'muicss/angular.js' {
  declare module.exports: $Exports<'muicss/angular'>;
}
declare module 'muicss/dist/angular/mui-angular.js' {
  declare module.exports: $Exports<'muicss/dist/angular/mui-angular'>;
}
declare module 'muicss/dist/angular/mui-angular.min.js' {
  declare module.exports: $Exports<'muicss/dist/angular/mui-angular.min'>;
}
declare module 'muicss/dist/extra/mui-angular-combined.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-angular-combined'>;
}
declare module 'muicss/dist/extra/mui-angular-combined.min.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-angular-combined.min'>;
}
declare module 'muicss/dist/extra/mui-combined.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-combined'>;
}
declare module 'muicss/dist/extra/mui-combined.min.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-combined.min'>;
}
declare module 'muicss/dist/extra/mui-react-combined.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-react-combined'>;
}
declare module 'muicss/dist/extra/mui-react-combined.min.js' {
  declare module.exports: $Exports<'muicss/dist/extra/mui-react-combined.min'>;
}
declare module 'muicss/dist/js/mui.js' {
  declare module.exports: $Exports<'muicss/dist/js/mui'>;
}
declare module 'muicss/dist/js/mui.min.js' {
  declare module.exports: $Exports<'muicss/dist/js/mui.min'>;
}
declare module 'muicss/dist/react/mui-react.js' {
  declare module.exports: $Exports<'muicss/dist/react/mui-react'>;
}
declare module 'muicss/dist/react/mui-react.min.js' {
  declare module.exports: $Exports<'muicss/dist/react/mui-react.min'>;
}
declare module 'muicss/dist/webcomponents/mui-webcomponents.js' {
  declare module.exports: $Exports<'muicss/dist/webcomponents/mui-webcomponents'>;
}
declare module 'muicss/dist/webcomponents/mui-webcomponents.min.js' {
  declare module.exports: $Exports<'muicss/dist/webcomponents/mui-webcomponents.min'>;
}
declare module 'muicss/index' {
  declare module.exports: $Exports<'muicss'>;
}
declare module 'muicss/index.js' {
  declare module.exports: $Exports<'muicss'>;
}
declare module 'muicss/lib/angular/appbar.js' {
  declare module.exports: $Exports<'muicss/lib/angular/appbar'>;
}
declare module 'muicss/lib/angular/babel-helpers.js' {
  declare module.exports: $Exports<'muicss/lib/angular/babel-helpers'>;
}
declare module 'muicss/lib/angular/button.js' {
  declare module.exports: $Exports<'muicss/lib/angular/button'>;
}
declare module 'muicss/lib/angular/caret.js' {
  declare module.exports: $Exports<'muicss/lib/angular/caret'>;
}
declare module 'muicss/lib/angular/checkbox.js' {
  declare module.exports: $Exports<'muicss/lib/angular/checkbox'>;
}
declare module 'muicss/lib/angular/col.js' {
  declare module.exports: $Exports<'muicss/lib/angular/col'>;
}
declare module 'muicss/lib/angular/container.js' {
  declare module.exports: $Exports<'muicss/lib/angular/container'>;
}
declare module 'muicss/lib/angular/divider.js' {
  declare module.exports: $Exports<'muicss/lib/angular/divider'>;
}
declare module 'muicss/lib/angular/dropdown-item.js' {
  declare module.exports: $Exports<'muicss/lib/angular/dropdown-item'>;
}
declare module 'muicss/lib/angular/dropdown.js' {
  declare module.exports: $Exports<'muicss/lib/angular/dropdown'>;
}
declare module 'muicss/lib/angular/form.js' {
  declare module.exports: $Exports<'muicss/lib/angular/form'>;
}
declare module 'muicss/lib/angular/input.js' {
  declare module.exports: $Exports<'muicss/lib/angular/input'>;
}
declare module 'muicss/lib/angular/option.js' {
  declare module.exports: $Exports<'muicss/lib/angular/option'>;
}
declare module 'muicss/lib/angular/panel.js' {
  declare module.exports: $Exports<'muicss/lib/angular/panel'>;
}
declare module 'muicss/lib/angular/radio.js' {
  declare module.exports: $Exports<'muicss/lib/angular/radio'>;
}
declare module 'muicss/lib/angular/row.js' {
  declare module.exports: $Exports<'muicss/lib/angular/row'>;
}
declare module 'muicss/lib/angular/select.js' {
  declare module.exports: $Exports<'muicss/lib/angular/select'>;
}
declare module 'muicss/lib/angular/tabs.js' {
  declare module.exports: $Exports<'muicss/lib/angular/tabs'>;
}
declare module 'muicss/lib/js/config.js' {
  declare module.exports: $Exports<'muicss/lib/js/config'>;
}
declare module 'muicss/lib/js/lib/forms.js' {
  declare module.exports: $Exports<'muicss/lib/js/lib/forms'>;
}
declare module 'muicss/lib/js/lib/jqLite.js' {
  declare module.exports: $Exports<'muicss/lib/js/lib/jqLite'>;
}
declare module 'muicss/lib/js/lib/util.js' {
  declare module.exports: $Exports<'muicss/lib/js/lib/util'>;
}
declare module 'muicss/lib/js/overlay.js' {
  declare module.exports: $Exports<'muicss/lib/js/overlay'>;
}
declare module 'muicss/lib/react/_helpers.js' {
  declare module.exports: $Exports<'muicss/lib/react/_helpers'>;
}
declare module 'muicss/lib/react/_textfieldHelpers.js' {
  declare module.exports: $Exports<'muicss/lib/react/_textfieldHelpers'>;
}
declare module 'muicss/lib/react/appbar.js' {
  declare module.exports: $Exports<'muicss/lib/react/appbar'>;
}
declare module 'muicss/lib/react/babel-helpers.js' {
  declare module.exports: $Exports<'muicss/lib/react/babel-helpers'>;
}
declare module 'muicss/lib/react/button.js' {
  declare module.exports: $Exports<'muicss/lib/react/button'>;
}
declare module 'muicss/lib/react/caret.js' {
  declare module.exports: $Exports<'muicss/lib/react/caret'>;
}
declare module 'muicss/lib/react/checkbox.js' {
  declare module.exports: $Exports<'muicss/lib/react/checkbox'>;
}
declare module 'muicss/lib/react/col.js' {
  declare module.exports: $Exports<'muicss/lib/react/col'>;
}
declare module 'muicss/lib/react/container.js' {
  declare module.exports: $Exports<'muicss/lib/react/container'>;
}
declare module 'muicss/lib/react/divider.js' {
  declare module.exports: $Exports<'muicss/lib/react/divider'>;
}
declare module 'muicss/lib/react/dropdown-item.js' {
  declare module.exports: $Exports<'muicss/lib/react/dropdown-item'>;
}
declare module 'muicss/lib/react/dropdown.js' {
  declare module.exports: $Exports<'muicss/lib/react/dropdown'>;
}
declare module 'muicss/lib/react/form.js' {
  declare module.exports: $Exports<'muicss/lib/react/form'>;
}
declare module 'muicss/lib/react/input.js' {
  declare module.exports: $Exports<'muicss/lib/react/input'>;
}
declare module 'muicss/lib/react/option.js' {
  declare module.exports: $Exports<'muicss/lib/react/option'>;
}
declare module 'muicss/lib/react/panel.js' {
  declare module.exports: $Exports<'muicss/lib/react/panel'>;
}
declare module 'muicss/lib/react/radio.js' {
  declare module.exports: $Exports<'muicss/lib/react/radio'>;
}
declare module 'muicss/lib/react/row.js' {
  declare module.exports: $Exports<'muicss/lib/react/row'>;
}
declare module 'muicss/lib/react/select.js' {
  declare module.exports: $Exports<'muicss/lib/react/select'>;
}
declare module 'muicss/lib/react/tab.js' {
  declare module.exports: $Exports<'muicss/lib/react/tab'>;
}
declare module 'muicss/lib/react/tabs.js' {
  declare module.exports: $Exports<'muicss/lib/react/tabs'>;
}
declare module 'muicss/lib/react/textarea.js' {
  declare module.exports: $Exports<'muicss/lib/react/textarea'>;
}
declare module 'muicss/react.js' {
  declare module.exports: $Exports<'muicss/react'>;
}
